steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.worker', '-t', 'us-central1-docker.pkg.dev/timelines-492720/cloud-run-source-deploy/feed-worker', '.']
images:
  - 'us-central1-docker.pkg.dev/timelines-492720/cloud-run-source-deploy/feed-worker'
