/**
 * Types for the Bluesky engagement introspection feature.
 *
 * Five signal types feed the pipeline (see introspection-design.html §1):
 *   like | repost | quote | post | reply
 *
 * Each engagement is hydrated into a `Subject` graph (recursive for quotes
 * and replies) so the LLM can read what was engaged with, not just the URI.
 */

export type SignalType = "like" | "repost" | "quote" | "post" | "reply";

/** What the user engaged with (or what they wrote, for own posts/quotes/replies). */
export interface Subject {
  uri: string;
  cid?: string;
  author: string; // handle, e.g. "@anil.bsky.social"
  authorDid?: string;
  text: string;
  // CIDs of attached images — bytes live on disk in the image cache.
  imageCids?: string[];
  // External link card content (no page-scraping).
  linkCard?: { title: string; description: string } | null;
  // Recursive: the post being quoted.
  quoting?: Subject | null;
  // Recursive: the post being replied to.
  replyingTo?: Subject | null;
  // True when getPosts couldn't hydrate this subject (deleted, blocked, 404).
  unavailable?: boolean;
}

/** One engagement record — what the Extractor sees. */
export interface Engagement {
  id: number;
  type: SignalType;
  ts: string; // ISO timestamp
  // The post the user acted on (or wrote, in the case of own post).
  subject: Subject;
  // The user's own words (set for quote / post / reply).
  userText?: string | null;
}

/** Deterministic, UI-only stats (NOT passed to the LLM). */
export interface Stats {
  total: number;
  rangeStart: string; // ISO
  rangeEnd: string; // ISO
  spanDays: number;
  avgPerDay: number;
  byType: Record<SignalType, { count: number; pct: number }>;
  imagePctByType: Partial<Record<SignalType, number>>;
  linkCardPctByType: Partial<Record<SignalType, number>>;
  avgQuoteWords: number;
  avgReplyWords: number;
  ratios: {
    repostToLike: number | null;
    quoteToRepost: number | null;
    ownToConsumed: number | null;
  };
  recent30d: {
    count: number;
    priorAvg30d: number;
    pctChange: number | null;
  };
  topAccounts: Array<{
    handle: string;
    total: number;
    byType: Partial<Record<SignalType, number>>;
  }>;
  unavailableCount: number;
}

/** Deterministic batch header (computed from records, no LLM). */
export interface BatchInfo {
  index: number; // 1-based, batch 1 = most-recent 100
  startTs: string; // ISO — oldest in this batch
  endTs: string; // ISO — newest in this batch
  engagementIds: number[];
  mix: Record<SignalType, number>;
  /** sha256 of sorted engagement URIs; invalidates the note on a refresh that shifts records. */
  hash: string;
}

/** LLM call telemetry — surfaced in the UI for demo legibility. */
export interface CallTelemetry {
  modelId: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens?: number;
  cacheCreationTokens?: number;
  costUsd: number;
  latencyMs: number;
  processedAt: string; // ISO
}

/** Stored Extractor output per batch. */
export interface BatchNote {
  batchIndex: number;
  hash: string; // matches BatchInfo.hash; invalidate if drifts
  /** ≤10-word title the Extractor emits on its first line; used as the collapsed-row summary. */
  headline?: string;
  text: string;
  telemetry: CallTelemetry;
  imagesAttached: number;
  imagesFailed: number;
}

/** Stored Aggregator output (regenerated on every click). */
export interface Profile {
  text: string;
  telemetry: CallTelemetry;
  fromBatchIndices: number[];
}

/**
 * Seed prompts the user can hand to the feed curator. Generated by an LLM
 * call chained after the Aggregator; 1–5 entries depending on how many
 * distinct directions the profile supports.
 */
export interface FeedSeedPrompts {
  prompts: string[];
  telemetry: CallTelemetry;
  generatedAt: string; // ISO
}

/** What lives on disk per handle. */
export interface Snapshot {
  handle: string;
  did: string;
  pds: string;
  fetchedAt: string; // ISO
  stats: Stats;
  engagements: Engagement[];
  batches: BatchInfo[];
  batchNotes: Record<number, BatchNote>;
  profile: Profile | null;
  feedSeedPrompts: FeedSeedPrompts | null;
  /** Every LLM call ever made for this handle (for cost transparency). */
  callHistory: CallTelemetry[];
}
