steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jetstream-indexer/worker:$BUILD_ID
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/jetstream-indexer/worker:latest
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/jetstream-indexer/worker:$BUILD_ID
  - us-central1-docker.pkg.dev/$PROJECT_ID/jetstream-indexer/worker:latest
options:
  logging: CLOUD_LOGGING_ONLY
