import type { MechanicalFilters } from "../types";
import {
  withMechanicalDefaults,
  DEFAULT_CANDIDATE_BUDGET,
  DEFAULT_RERANK_MODEL,
} from "../defaults";
import { query } from "./connection";

// --- Feeds ---

export interface DbFeed {
  id: number;
  user_id: string;
  name: string;
  mechanical_filters: MechanicalFilters;
  subqueries: string[];
  candidate_budget: number;
  // Free-form rerank prompt generated by the curator agent for this feed.
  // Empty string = no rerank, just vector order.
  rerank_prompt: string;
  // Anthropic model used for rerank. Defaults to DEFAULT_RERANK_MODEL.
  rerank_model: string;
  // When true, pass extended-thinking config to the rerank model.
  rerank_thinking_enabled: boolean;
  published_rkey: string | null;
  is_active: boolean;
  color: string | null;
  // Branch lineage. Set when this feed was created by branching off a post;
  // null for normal feeds. See DECISIONS.md (#3, #6).
  parent_feed_id: number | null;
  source_post_uri: string | null;
  created_at: Date;
  updated_at: Date;
}

interface DbFeedRow {
  id: number;
  user_id: string;
  name: string;
  mechanical_filters: MechanicalFilters | string;
  subqueries: string[] | string | null;
  candidate_budget: number | null;
  rerank_prompt: string | null;
  rerank_model: string | null;
  rerank_thinking_enabled: boolean | null;
  published_rkey: string | null;
  is_active: boolean;
  color: string | null;
  parent_feed_id: number | null;
  source_post_uri: string | null;
  created_at: Date;
  updated_at: Date;
}

function parseJsonCol<T>(val: T | string): T {
  return typeof val === "string" ? JSON.parse(val) : val;
}

export function rowToFeed(row: DbFeedRow): DbFeed {
  const mech = withMechanicalDefaults(
    parseJsonCol<Partial<MechanicalFilters>>(row.mechanical_filters ?? {})
  );
  const subsRaw = row.subqueries == null ? [] : parseJsonCol<unknown>(row.subqueries);
  const subqueries = Array.isArray(subsRaw)
    ? subsRaw.filter((s): s is string => typeof s === "string")
    : [];
  return {
    id: row.id,
    user_id: row.user_id,
    name: row.name,
    mechanical_filters: mech,
    subqueries,
    candidate_budget:
      typeof row.candidate_budget === "number" && row.candidate_budget > 0
        ? row.candidate_budget
        : DEFAULT_CANDIDATE_BUDGET,
    rerank_prompt: row.rerank_prompt ?? "",
    rerank_model:
      row.rerank_model && row.rerank_model.length > 0
        ? row.rerank_model
        : DEFAULT_RERANK_MODEL,
    rerank_thinking_enabled: row.rerank_thinking_enabled === true,
    published_rkey: row.published_rkey,
    is_active: row.is_active,
    color: row.color,
    parent_feed_id: row.parent_feed_id ?? null,
    source_post_uri: row.source_post_uri ?? null,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

export async function createFeed(
  userId: string,
  name: string = "Untitled"
): Promise<DbFeed> {
  const res = await query(
    `INSERT INTO feeds (user_id, name) VALUES ($1, $2) RETURNING *`,
    [userId, name]
  );
  return rowToFeed(res.rows[0]);
}

/**
 * Create a feed by branching off a post. Seeds the picked categories as
 * subqueries and records lineage (parent_feed_id + source_post_uri). The
 * rerank_prompt + a polished name are filled later by the seeded chat agent
 * on its first turn — see /api/chat branch-init. See DECISIONS.md (#4, #8).
 */
export async function createBranchedFeed(
  userId: string,
  opts: {
    name: string;
    subqueries: string[];
    parentFeedId: number;
    sourcePostUri: string;
  }
): Promise<DbFeed> {
  const res = await query(
    `INSERT INTO feeds (user_id, name, subqueries, parent_feed_id, source_post_uri)
     VALUES ($1, $2, $3::jsonb, $4, $5) RETURNING *`,
    [
      userId,
      opts.name,
      JSON.stringify(opts.subqueries),
      opts.parentFeedId,
      opts.sourcePostUri,
    ]
  );
  return rowToFeed(res.rows[0]);
}

export async function getFeed(id: number): Promise<DbFeed | null> {
  const res = await query("SELECT * FROM feeds WHERE id = $1", [id]);
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function getFeedForUser(
  id: number,
  userId: string
): Promise<DbFeed | null> {
  const res = await query(
    "SELECT * FROM feeds WHERE id = $1 AND user_id = $2",
    [id, userId]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function listFeedsForUser(userId: string): Promise<DbFeed[]> {
  const res = await query(
    "SELECT * FROM feeds WHERE user_id = $1 ORDER BY updated_at DESC",
    [userId]
  );
  return res.rows.map(rowToFeed);
}

export async function getFeedByRkey(rkey: string): Promise<DbFeed | null> {
  const res = await query(
    "SELECT * FROM feeds WHERE published_rkey = $1",
    [rkey]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

/** No-ownership lookup — used by the public share page (/f/[feedId]). */
export async function getFeedById(id: number): Promise<DbFeed | null> {
  const res = await query("SELECT * FROM feeds WHERE id = $1", [id]);
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function getPublishedFeed(
  rkey: string,
  publisherDid?: string
): Promise<DbFeed | null> {
  if (publisherDid) {
    const res = await query(
      `SELECT f.* FROM feeds f
       JOIN users u ON u.id = f.user_id
       WHERE f.published_rkey = $1 AND u.bluesky_did = $2`,
      [rkey, publisherDid]
    );
    return res.rows[0] ? rowToFeed(res.rows[0]) : null;
  }
  return getFeedByRkey(rkey);
}

export interface PublishedFeedEntry {
  feed: DbFeed;
  publisher_did: string;
}

export async function getPublishedFeedsWithPublisher(): Promise<PublishedFeedEntry[]> {
  const res = await query(
    `SELECT f.*, u.bluesky_did AS publisher_did
     FROM feeds f
     JOIN users u ON u.id = f.user_id
     WHERE f.published_rkey IS NOT NULL
       AND u.bluesky_did IS NOT NULL
     ORDER BY f.updated_at DESC`
  );
  return res.rows.map((row) => ({
    feed: rowToFeed(row),
    publisher_did: row.publisher_did as string,
  }));
}

export async function getActiveFeeds(): Promise<DbFeed[]> {
  const res = await query(
    "SELECT * FROM feeds WHERE is_active = true ORDER BY id"
  );
  return res.rows.map(rowToFeed);
}

export async function updateFeed(
  id: number,
  updates: {
    name?: string;
    mechanical_filters?: MechanicalFilters;
    subqueries?: string[];
    candidate_budget?: number;
    rerank_prompt?: string;
    rerank_model?: string;
    rerank_thinking_enabled?: boolean;
    published_rkey?: string;
    is_active?: boolean;
    color?: string;
  }
): Promise<DbFeed | null> {
  const feed = await getFeed(id);
  if (!feed) return null;

  const res = await query(
    `UPDATE feeds SET
       name = $1,
       mechanical_filters = $2, subqueries = $3, candidate_budget = $4,
       rerank_prompt = $5, rerank_model = $6, rerank_thinking_enabled = $7,
       published_rkey = $8, is_active = $9, color = $10,
       updated_at = now()
     WHERE id = $11 RETURNING *`,
    [
      updates.name ?? feed.name,
      JSON.stringify(updates.mechanical_filters ?? feed.mechanical_filters),
      JSON.stringify(updates.subqueries ?? feed.subqueries),
      updates.candidate_budget ?? feed.candidate_budget,
      updates.rerank_prompt ?? feed.rerank_prompt,
      updates.rerank_model ?? feed.rerank_model,
      updates.rerank_thinking_enabled ?? feed.rerank_thinking_enabled,
      updates.published_rkey ?? feed.published_rkey,
      updates.is_active ?? feed.is_active,
      updates.color ?? feed.color,
      id,
    ]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function deleteFeed(id: number): Promise<void> {
  await query("DELETE FROM chat_messages WHERE feed_id = $1", [id]);
  await query("DELETE FROM feeds WHERE id = $1", [id]);
}
