import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { Pool } from "pg";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const SCHEMA = `
-- Enable pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  firebase_uid TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  photo_url TEXT,
  bluesky_handle TEXT,
  bluesky_did TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_firebase ON users(firebase_uid);

-- Feeds (user-scoped, stores full config as JSONB).
-- Curator redesign: semantic_config is replaced by `subqueries` (a JSONB
-- string array, designed for ANN) and `candidate_budget` (total k across
-- all subqueries). See DECISIONS.md.
CREATE TABLE IF NOT EXISTS feeds (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Untitled',
  mechanical_filters JSONB NOT NULL DEFAULT '{}',
  subqueries JSONB NOT NULL DEFAULT '[]',
  candidate_budget INT NOT NULL DEFAULT 150,
  published_rkey TEXT,
  is_active BOOLEAN DEFAULT true,
  color TEXT,
  -- Branch lineage: set when this feed was created by branching off a post.
  -- parent_feed_id is the feed the user branched from; source_post_uri is the
  -- at:// URI of the post that sparked the branch. Both NULL for normal feeds.
  parent_feed_id INT REFERENCES feeds(id) ON DELETE SET NULL,
  source_post_uri TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_feeds_user ON feeds(user_id);
CREATE INDEX IF NOT EXISTS idx_feeds_active ON feeds(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_feeds_parent ON feeds(parent_feed_id) WHERE parent_feed_id IS NOT NULL;

-- Migration for pre-redesign databases: add the new columns and drop dead ones.
-- Idempotent — safe to run repeatedly.
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS subqueries JSONB NOT NULL DEFAULT '[]';
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS candidate_budget INT NOT NULL DEFAULT 150;
-- Per-feed rerank prompt — generated by the curator agent, free-form text.
-- Empty string means "no rerank, just vector order."
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS rerank_prompt TEXT NOT NULL DEFAULT '';
-- Branch lineage columns (see CREATE TABLE above). Additive + nullable.
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS parent_feed_id INT REFERENCES feeds(id) ON DELETE SET NULL;
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS source_post_uri TEXT;
CREATE INDEX IF NOT EXISTS idx_feeds_parent ON feeds(parent_feed_id) WHERE parent_feed_id IS NOT NULL;
ALTER TABLE feeds DROP COLUMN IF EXISTS semantic_config;
ALTER TABLE feeds DROP COLUMN IF EXISTS description;
ALTER TABLE feeds DROP COLUMN IF EXISTS rerank_prompt_id;

-- Chat messages (per-feed)
CREATE TABLE IF NOT EXISTS chat_messages (
  id SERIAL PRIMARY KEY,
  feed_id INT NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Mailing list subscribers
CREATE TABLE IF NOT EXISTS subscribers (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);
`;

async function main() {
  console.log("Setting up PostgreSQL schema...");
  console.log(`Database: ${process.env.DATABASE_URL?.replace(/:[^@]+@/, ":***@")}`);

  try {
    await pool.query(SCHEMA);
    console.log("Schema created successfully.");

    // Verify tables
    const tables = await pool.query(
      `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name`
    );
    console.log(
      "Tables:",
      tables.rows.map((r: { table_name: string }) => r.table_name).join(", ")
    );
  } catch (err: any) {
    console.error("Setup failed:", err.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
