import { Pool, type PoolClient, type QueryResult } from "pg";
import { Connector, IpAddressTypes } from "@google-cloud/cloud-sql-connector";
import type { MechanicalFilters } from "./types";
import {
  withMechanicalDefaults,
  DEFAULT_CANDIDATE_BUDGET,
  DEFAULT_RERANK_MODEL,
} from "./defaults";
import { searchPosts, type SearchFilter } from "./vector-search";
import { rerank } from "./rerank";
import { getSecret } from "./secrets";
import { onAdcChange } from "./adc-watcher";

// --- Connection Pool ---
// We talk to Cloud SQL via @google-cloud/cloud-sql-connector in both local
// dev and on Cloud Run. The connector authenticates via ADC, fetches an
// ephemeral cert from the SQL Admin API, and opens a TLS tunnel directly to
// the instance — no IP allowlist, no `--add-cloudsql-instances` flag, no
// unix socket. Same code path everywhere.
//
// We still pull DATABASE_URL from Secret Manager so the password isn't
// hardcoded; we just parse the connection string and feed user/password/
// database to the pool, while the connector replaces the network stream.

const INSTANCE_CONNECTION_NAME =
  process.env.CLOUDSQL_CONNECTION_NAME ??
  "timelines-492720:us-central1:feed-db";

let _pool: Pool | null = null;
let _poolInit: Promise<Pool> | null = null;
let _connector: Connector | null = null;

onAdcChange(() => {
  const had = _pool !== null || _poolInit !== null || _connector !== null;
  if (_pool) { _pool.end().catch(() => { /* ignore */ }); }
  _pool = null;
  _poolInit = null;
  if (_connector) { try { _connector.close(); } catch { /* ignore */ } }
  _connector = null;
  if (had) console.log("[pg] feed-db pool/connector reset after ADC change");
});

export async function getPool(): Promise<Pool> {
  if (_pool) return _pool;
  if (_poolInit) return _poolInit;
  const init = (async () => {
    const dsn = await getSecret("database-url");
    const u = new URL(dsn);
    const user = decodeURIComponent(u.username);
    const password = decodeURIComponent(u.password);
    const database = u.pathname.replace(/^\//, "") || "postgres";

    _connector = new Connector();
    const clientOpts = await _connector.getOptions({
      instanceConnectionName: INSTANCE_CONNECTION_NAME,
      ipType: IpAddressTypes.PUBLIC,
    });

    const pool = new Pool({
      ...clientOpts,
      user,
      password,
      database,
      max: 20,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 5_000,
    });
    pool.on("error", (err) => {
      console.error("[pg] Unexpected pool error:", err.message);
    });
    _pool = pool;
    return pool;
  })();
  // Cache only successful inits — on rejection, clear so the next call retries.
  _poolInit = init;
  init.catch((err) => {
    console.error("[pg] pool init failed:", err?.code, err?.message ?? err);
    if (_poolInit === init) _poolInit = null;
  });
  return init;
}

export async function query(
  text: string,
  params?: unknown[]
): Promise<QueryResult> {
  const pool = await getPool();
  return pool.query(text, params);
}

export async function withClient<T>(
  fn: (client: PoolClient) => Promise<T>
): Promise<T> {
  const pool = await getPool();
  const client = await pool.connect();
  try {
    return await fn(client);
  } finally {
    client.release();
  }
}

// --- User ---

export interface DbUser {
  id: string; // UUID
  firebase_uid: string;
  name: string;
  email: string;
  photo_url: string | null;
  bluesky_handle: string | null;
  bluesky_did: string | null;
  created_at: Date;
  updated_at: Date;
}

export async function upsertUser(params: {
  firebaseUid: string;
  name: string;
  email: string;
  photoUrl?: string;
  blueskyHandle?: string;
  blueskyDid?: string;
}): Promise<DbUser> {
  const res = await query(
    `INSERT INTO users (firebase_uid, name, email, photo_url, bluesky_handle, bluesky_did)
     VALUES ($1, $2, $3, $4, $5, $6)
     ON CONFLICT (firebase_uid) DO UPDATE SET
       name = EXCLUDED.name,
       email = EXCLUDED.email,
       photo_url = COALESCE(EXCLUDED.photo_url, users.photo_url),
       bluesky_handle = COALESCE(EXCLUDED.bluesky_handle, users.bluesky_handle),
       bluesky_did = COALESCE(EXCLUDED.bluesky_did, users.bluesky_did),
       updated_at = now()
     RETURNING *`,
    [
      params.firebaseUid,
      params.name,
      params.email,
      params.photoUrl ?? null,
      params.blueskyHandle ?? null,
      params.blueskyDid ?? null,
    ]
  );
  return res.rows[0];
}

export async function getUserByFirebaseUid(
  firebaseUid: string
): Promise<DbUser | null> {
  const res = await query("SELECT * FROM users WHERE firebase_uid = $1", [
    firebaseUid,
  ]);
  return res.rows[0] ?? null;
}

// --- Feeds ---

export interface DbFeed {
  id: number;
  user_id: string;
  name: string;
  mechanical_filters: MechanicalFilters;
  subqueries: string[];
  candidate_budget: number;
  // Free-form rerank prompt generated by the curator agent for this feed.
  // Empty string = no rerank, just vector order.
  rerank_prompt: string;
  // Anthropic model used for rerank. Defaults to DEFAULT_RERANK_MODEL.
  rerank_model: string;
  published_rkey: string | null;
  is_active: boolean;
  color: string | null;
  created_at: Date;
  updated_at: Date;
}

interface DbFeedRow {
  id: number;
  user_id: string;
  name: string;
  mechanical_filters: MechanicalFilters | string;
  subqueries: string[] | string | null;
  candidate_budget: number | null;
  rerank_prompt: string | null;
  rerank_model: string | null;
  published_rkey: string | null;
  is_active: boolean;
  color: string | null;
  created_at: Date;
  updated_at: Date;
}

function parseJsonCol<T>(val: T | string): T {
  return typeof val === "string" ? JSON.parse(val) : val;
}

function rowToFeed(row: DbFeedRow): DbFeed {
  const mech = withMechanicalDefaults(
    parseJsonCol<Partial<MechanicalFilters>>(row.mechanical_filters ?? {})
  );
  const subsRaw = row.subqueries == null ? [] : parseJsonCol<unknown>(row.subqueries);
  const subqueries = Array.isArray(subsRaw)
    ? subsRaw.filter((s): s is string => typeof s === "string")
    : [];
  return {
    id: row.id,
    user_id: row.user_id,
    name: row.name,
    mechanical_filters: mech,
    subqueries,
    candidate_budget:
      typeof row.candidate_budget === "number" && row.candidate_budget > 0
        ? row.candidate_budget
        : DEFAULT_CANDIDATE_BUDGET,
    rerank_prompt: row.rerank_prompt ?? "",
    rerank_model:
      row.rerank_model && row.rerank_model.length > 0
        ? row.rerank_model
        : DEFAULT_RERANK_MODEL,
    published_rkey: row.published_rkey,
    is_active: row.is_active,
    color: row.color,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

export async function createFeed(
  userId: string,
  name: string = "Untitled"
): Promise<DbFeed> {
  const res = await query(
    `INSERT INTO feeds (user_id, name) VALUES ($1, $2) RETURNING *`,
    [userId, name]
  );
  return rowToFeed(res.rows[0]);
}

export async function getFeed(id: number): Promise<DbFeed | null> {
  const res = await query("SELECT * FROM feeds WHERE id = $1", [id]);
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function getFeedForUser(
  id: number,
  userId: string
): Promise<DbFeed | null> {
  const res = await query(
    "SELECT * FROM feeds WHERE id = $1 AND user_id = $2",
    [id, userId]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function listFeedsForUser(userId: string): Promise<DbFeed[]> {
  const res = await query(
    "SELECT * FROM feeds WHERE user_id = $1 ORDER BY updated_at DESC",
    [userId]
  );
  return res.rows.map(rowToFeed);
}

export async function getFeedByRkey(rkey: string): Promise<DbFeed | null> {
  const res = await query(
    "SELECT * FROM feeds WHERE published_rkey = $1",
    [rkey]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function getActiveFeeds(): Promise<DbFeed[]> {
  const res = await query(
    "SELECT * FROM feeds WHERE is_active = true ORDER BY id"
  );
  return res.rows.map(rowToFeed);
}

export async function updateFeed(
  id: number,
  updates: {
    name?: string;
    mechanical_filters?: MechanicalFilters;
    subqueries?: string[];
    candidate_budget?: number;
    rerank_prompt?: string;
    rerank_model?: string;
    published_rkey?: string;
    is_active?: boolean;
    color?: string;
  }
): Promise<DbFeed | null> {
  const feed = await getFeed(id);
  if (!feed) return null;

  const res = await query(
    `UPDATE feeds SET
       name = $1,
       mechanical_filters = $2, subqueries = $3, candidate_budget = $4,
       rerank_prompt = $5, rerank_model = $6,
       published_rkey = $7, is_active = $8, color = $9,
       updated_at = now()
     WHERE id = $10 RETURNING *`,
    [
      updates.name ?? feed.name,
      JSON.stringify(updates.mechanical_filters ?? feed.mechanical_filters),
      JSON.stringify(updates.subqueries ?? feed.subqueries),
      updates.candidate_budget ?? feed.candidate_budget,
      updates.rerank_prompt ?? feed.rerank_prompt,
      updates.rerank_model ?? feed.rerank_model,
      updates.published_rkey ?? feed.published_rkey,
      updates.is_active ?? feed.is_active,
      updates.color ?? feed.color,
      id,
    ]
  );
  return res.rows[0] ? rowToFeed(res.rows[0]) : null;
}

export async function deleteFeed(id: number): Promise<void> {
  await query("DELETE FROM chat_messages WHERE feed_id = $1", [id]);
  await query("DELETE FROM feeds WHERE id = $1", [id]);
}

// --- Posts ---
// Posts come from a Vertex AI Vector Search index of Bluesky Jetstream
// (the index lives in `amir-experimental`, fed by happy-feed's worker).
// We embed the feed's topics + keywords + vibes with Gemini and
// query the index directly — see src/lib/vector-search.ts.

// Translate MechanicalFilters → Vertex SearchFilter. Only wired fields remain
// after the curator redesign. `post_type` "all" leaves the reply restrict off
// so both replies and top-level posts come back.
function mechanicalToSearchFilter(m?: MechanicalFilters): SearchFilter | undefined {
  if (!m) return undefined;
  const f: SearchFilter = {};
  let any = false;
  if (m.lang_allow?.length) { f.lang = m.lang_allow; any = true; }
  if (m.post_type === "top_level") { f.isReply = false; any = true; }
  if (m.post_type === "replies") { f.isReply = true; any = true; }
  if (m.require_media) { f.hasImages = true; any = true; }
  else if (m.exclude_media) { f.hasImages = false; any = true; }
  if (m.require_video) { f.hasVideo = true; any = true; }
  else if (m.exclude_video) { f.hasVideo = false; any = true; }
  if (m.require_link) { f.hasExternalLink = true; any = true; }
  else if (m.exclude_links) { f.hasExternalLink = false; any = true; }
  if (m.require_quote) { f.hasQuote = true; any = true; }
  if (m.hashtag_include?.length) {
    f.hashtags = m.hashtag_include.map((t) => t.toLowerCase());
    any = true;
  }
  if (m.block_labels?.length) { f.selfLabelsDeny = m.block_labels; any = true; }
  if (m.exclude_likely_nsfw) { f.excludeLikelyNsfw = true; any = true; }
  if (m.min_like_count > 0) { f.minLikeCount = m.min_like_count; any = true; }
  if (m.min_repost_count > 0) { f.minRepostCount = m.min_repost_count; any = true; }
  if (m.min_reply_count > 0) { f.minReplyCount = m.min_reply_count; any = true; }

  const bounds = timeWindowToBounds(m);
  if (bounds.afterUs !== undefined) { f.createdAfterUs = bounds.afterUs; any = true; }
  if (bounds.beforeUs !== undefined) { f.createdBeforeUs = bounds.beforeUs; any = true; }

  return any ? f : undefined;
}

const PRESET_WINDOW_MS: Record<string, number> = {
  "1h": 60 * 60 * 1000,
  "24h": 24 * 60 * 60 * 1000,
  "7d": 7 * 24 * 60 * 60 * 1000,
  "30d": 30 * 24 * 60 * 60 * 1000,
};

function timeWindowToBounds(m: MechanicalFilters): {
  afterUs?: number;
  beforeUs?: number;
} {
  const window = m.time_window;
  if (!window || window === "all") return {};
  if (window === "custom") {
    const out: { afterUs?: number; beforeUs?: number } = {};
    if (m.created_after_iso) {
      const t = Date.parse(m.created_after_iso);
      if (!Number.isNaN(t)) out.afterUs = t * 1000;
    }
    if (m.created_before_iso) {
      const t = Date.parse(m.created_before_iso);
      if (!Number.isNaN(t)) out.beforeUs = t * 1000;
    }
    return out;
  }
  const delta = PRESET_WINDOW_MS[window];
  if (!delta) return {};
  return { afterUs: (Date.now() - delta) * 1000 };
}

export interface FeedPreviewPost {
  uri: string;
  text: string;
  author_did: string;
  author_handle: string | null;
  author_display_name: string | null;
  author_avatar_cid: string | null;
  score: number;
  // Set when the feed has a rerank prompt and the rerank call succeeded.
  // 0–100, as returned by the LLM. Independent of `score` (cosine similarity).
  rerank_score?: number;
  rerank_reason?: string;
  // Heuristic flag from the author's description (see LIKE_NSFW_DESCRIPTION_KEYWORDS).
  // Hits flagged true are dropped before rerank when exclude_likely_nsfw is on;
  // we still surface the field so the UI debug strip can show it for tuning.
  like_nsfw: boolean;
  indexed_at: string;
  like_count: number;
  repost_count: number;
  reply_count: number;
  quote_count: number;
  external_uri: string | null;
  external_title: string | null;
  external_desc: string | null;
  quote_uri: string | null;
  has_images: boolean;
  image_count: number;
  image_alts: string[];
  is_reply: boolean;
  reply_parent_uri: string | null;
}

// Pipeline stage names surfaced to the streaming loader. Mirrors the
// frontend's PipelineLoader component states.
//   searching → Vertex ANN + hydrate + AppView meta + author profiles
//   thinking  → request sent to Claude, model processing before any output
//                (TTFT today; would surface real thinking deltas if extended
//                 thinking were enabled on the rerank call)
//   ranking   → model emitting the sorted JSON output token-by-token
//   done      → final posts ready
export type PreviewStage =
  | "searching"
  | "thinking"
  | "ranking"
  | "done"
  | "skipped_rerank";

export interface PreviewStageEvent {
  stage: PreviewStage;
  // Set on "thinking" — counts surfaced to the loader sub-line.
  candidates?: number;  // candidates actually sent to the reranker (capped)
  hits?: number;        // total vector-search hits before the cap
  images?: number;
  model?: string;
}

export async function getFeedPreviewPosts(
  feedId: number,
  limit: number = 25,
  onStage?: (e: PreviewStageEvent) => void
): Promise<FeedPreviewPost[]> {
  const t0 = performance.now();
  const feedRes = await query("SELECT * FROM feeds WHERE id = $1", [feedId]);
  if (feedRes.rows.length === 0) return [];
  const feed = rowToFeed(feedRes.rows[0]);
  const tFeed = performance.now();

  if (feed.subqueries.length === 0) {
    onStage?.({ stage: "done" });
    return [];
  }

  const filter = mechanicalToSearchFilter(feed.mechanical_filters);
  onStage?.({ stage: "searching" });

  try {
    const willRerank = feed.rerank_prompt.trim().length > 0;
    const hits = await searchPosts({
      subqueries: feed.subqueries,
      totalBudget: feed.candidate_budget,
      filter,
      // Only round-trip the AppView for image URLs when we'll actually
      // pass them into the reranker.
      withImages: willRerank,
    });
    const tSearch = performance.now();

    // Map of post index → {score, reason} from the reranker, if one ran.
    let rerankByIndex: Map<number, { score: number; reason: string }> | null = null;
    let orderedHits = hits;
    let msRerank = 0;
    let rerankAttempted = false;

    if (!willRerank) {
      onStage?.({ stage: "skipped_rerank" });
    }
    if (willRerank && hits.length > 0) {
      rerankAttempted = true;
      try {
        // The reranker sees every candidate that survived the vector-search
        // pipeline. Per-feed `candidate_budget` (Advanced → N) is the only
        // knob — bump it down if rerank latency is hurting, bump it up to
        // give the reranker a wider net.
        const r = await rerank({
          // Joining subqueries with " | " lets the rerank prompt see all
          // intents at once without needing rewrites.
          query: feed.subqueries.join(" | "),
          candidates: hits,
          topK: limit,
          systemPrompt: feed.rerank_prompt,
          model: feed.rerank_model,
          withImages: true,
          onRequestSent: ({ candidates, images, model }) => {
            onStage?.({
              stage: "thinking",
              candidates,
              hits: hits.length,
              images,
              model,
            });
          },
          onFirstToken: () => {
            onStage?.({ stage: "ranking" });
          },
        });
        msRerank = r.ms_rerank;
        rerankByIndex = new Map();
        orderedHits = [];
        for (const k of r.kept) {
          if (k.i < 0 || k.i >= hits.length) continue;
          rerankByIndex.set(k.i, { score: k.score, reason: k.reason });
          orderedHits.push(hits[k.i]);
        }
      } catch (e) {
        // Reranker failure → fall back to vector order. Surface raw hits
        // rather than fail the whole preview.
        console.warn(
          "[rerank] failed, falling back to vector order:",
          e instanceof Error ? e.message : String(e)
        );
      }
    }

    const sliced = orderedHits.slice(0, limit);
    console.log(
      `[timing] getFeedPreviewPosts feed-lookup=${(tFeed - t0).toFixed(0)}ms ` +
        `searchPosts=${(tSearch - tFeed).toFixed(0)}ms ` +
        (rerankAttempted ? `rerank=${msRerank}ms ` : "") +
        `total=${(performance.now() - t0).toFixed(0)}ms feedId=${feedId} ` +
        `subqueries=${feed.subqueries.length} budget=${feed.candidate_budget} ` +
        `hits=${hits.length} ` +
        (rerankByIndex ? `kept=${rerankByIndex.size} ` : "") +
        `returned=${sliced.length}`
    );
    return sliced.map((h) => {
      // Find this hit's original index in the unranked list to look up its
      // reranker fields. orderedHits already maps through r.kept, but we
      // need the original index to read rerankByIndex.
      const origIdx = hits.indexOf(h);
      const rr = rerankByIndex && origIdx >= 0 ? rerankByIndex.get(origIdx) : undefined;
      return {
        uri: h.uri,
        text: h.text,
        author_did: h.did,
        author_handle: h.author_handle,
        author_display_name: h.author_display_name,
        author_avatar_cid: h.author_avatar_cid,
        score: h.vector_score,
        rerank_score: rr?.score,
        rerank_reason: rr?.reason,
        like_nsfw: h.like_nsfw,
        indexed_at: h.created_at,
        like_count: h.like_count ?? 0,
        repost_count: h.repost_count ?? 0,
        reply_count: h.reply_count ?? 0,
        quote_count: h.quote_count ?? 0,
        external_uri: h.external_uri,
        external_title: h.external_title,
        external_desc: h.external_desc,
        quote_uri: h.quote_uri,
        has_images: h.has_images,
        image_count: h.image_count,
        image_alts: h.image_alts,
        is_reply: h.is_reply,
        reply_parent_uri: h.reply_parent_uri,
      };
    });
  } catch (e) {
    console.warn(
      "[vector-search] search failed:",
      e instanceof Error ? e.message : String(e)
    );
    return [];
  }
}

// --- Chat Messages ---

export async function getChatMessages(
  feedId: number
): Promise<{ role: string; content: string }[]> {
  const res = await query(
    "SELECT role, content FROM chat_messages WHERE feed_id = $1 ORDER BY id ASC",
    [feedId]
  );
  return res.rows;
}

export async function addChatMessage(
  feedId: number,
  role: "user" | "assistant",
  content: string
): Promise<void> {
  await query(
    "INSERT INTO chat_messages (feed_id, role, content) VALUES ($1, $2, $3)",
    [feedId, role, content]
  );
}

export async function clearChat(feedId: number): Promise<void> {
  await query("DELETE FROM chat_messages WHERE feed_id = $1", [feedId]);
}

// --- Mailing list ---

export async function addSubscriber(email: string): Promise<{ created: boolean }> {
  const res = await query(
    `INSERT INTO subscribers (email) VALUES ($1)
     ON CONFLICT (email) DO NOTHING
     RETURNING id`,
    [email]
  );
  return { created: res.rowCount === 1 };
}

// --- Reranker prompts (used by /search) ---

export interface DbRerankPrompt {
  id: string;
  user_id: string;
  name: string;
  current_version_id: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface DbRerankPromptVersion {
  id: string;
  prompt_id: string;
  version: number;
  system_prompt: string;
  created_at: Date;
}

export interface RerankPromptWithVersion extends DbRerankPrompt {
  current_version: number | null;
  current_system_prompt: string | null;
}

export async function listRerankPromptsForUser(
  userId: string
): Promise<RerankPromptWithVersion[]> {
  const res = await query(
    `SELECT p.*,
            v.version       AS current_version,
            v.system_prompt AS current_system_prompt
       FROM rerank_prompts p
       LEFT JOIN rerank_prompt_versions v ON v.id = p.current_version_id
      WHERE p.user_id = $1
      ORDER BY p.updated_at DESC`,
    [userId]
  );
  return res.rows;
}

export async function getRerankPromptForUser(
  id: string,
  userId: string
): Promise<RerankPromptWithVersion | null> {
  const res = await query(
    `SELECT p.*,
            v.version       AS current_version,
            v.system_prompt AS current_system_prompt
       FROM rerank_prompts p
       LEFT JOIN rerank_prompt_versions v ON v.id = p.current_version_id
      WHERE p.id = $1 AND p.user_id = $2`,
    [id, userId]
  );
  return res.rows[0] ?? null;
}

export async function listRerankPromptVersions(
  promptId: string
): Promise<DbRerankPromptVersion[]> {
  const res = await query(
    `SELECT * FROM rerank_prompt_versions
      WHERE prompt_id = $1
      ORDER BY version DESC`,
    [promptId]
  );
  return res.rows;
}

export async function createRerankPrompt(opts: {
  userId: string;
  name: string;
  systemPrompt: string;
}): Promise<RerankPromptWithVersion> {
  return withClient(async (c) => {
    await c.query("BEGIN");
    try {
      const promptRes = await c.query<DbRerankPrompt>(
        `INSERT INTO rerank_prompts (user_id, name) VALUES ($1, $2) RETURNING *`,
        [opts.userId, opts.name]
      );
      const prompt = promptRes.rows[0];
      const versionRes = await c.query<DbRerankPromptVersion>(
        `INSERT INTO rerank_prompt_versions (prompt_id, version, system_prompt)
         VALUES ($1, 1, $2) RETURNING *`,
        [prompt.id, opts.systemPrompt]
      );
      const version = versionRes.rows[0];
      await c.query(
        `UPDATE rerank_prompts SET current_version_id = $1, updated_at = now() WHERE id = $2`,
        [version.id, prompt.id]
      );
      await c.query("COMMIT");
      return {
        ...prompt,
        current_version_id: version.id,
        current_version: version.version,
        current_system_prompt: version.system_prompt,
      };
    } catch (e) {
      await c.query("ROLLBACK");
      throw e;
    }
  });
}

export async function renameRerankPrompt(
  id: string,
  userId: string,
  name: string
): Promise<void> {
  await query(
    `UPDATE rerank_prompts SET name = $1, updated_at = now()
      WHERE id = $2 AND user_id = $3`,
    [name, id, userId]
  );
}

export async function saveRerankPromptVersion(opts: {
  promptId: string;
  userId: string;
  systemPrompt: string;
}): Promise<DbRerankPromptVersion> {
  return withClient(async (c) => {
    await c.query("BEGIN");
    try {
      // Verify ownership inside the transaction.
      const own = await c.query(
        `SELECT id FROM rerank_prompts WHERE id = $1 AND user_id = $2 FOR UPDATE`,
        [opts.promptId, opts.userId]
      );
      if (own.rowCount === 0) {
        await c.query("ROLLBACK");
        throw new Error("prompt not found");
      }
      const maxRes = await c.query<{ max: number | null }>(
        `SELECT MAX(version) AS max FROM rerank_prompt_versions WHERE prompt_id = $1`,
        [opts.promptId]
      );
      const nextVersion = (maxRes.rows[0]?.max ?? 0) + 1;
      const versionRes = await c.query<DbRerankPromptVersion>(
        `INSERT INTO rerank_prompt_versions (prompt_id, version, system_prompt)
         VALUES ($1, $2, $3) RETURNING *`,
        [opts.promptId, nextVersion, opts.systemPrompt]
      );
      const version = versionRes.rows[0];
      await c.query(
        `UPDATE rerank_prompts SET current_version_id = $1, updated_at = now() WHERE id = $2`,
        [version.id, opts.promptId]
      );
      await c.query("COMMIT");
      return version;
    } catch (e) {
      await c.query("ROLLBACK");
      throw e;
    }
  });
}

export async function activateRerankPromptVersion(opts: {
  promptId: string;
  userId: string;
  versionId: string;
}): Promise<void> {
  const res = await query(
    `UPDATE rerank_prompts
        SET current_version_id = $1, updated_at = now()
      WHERE id = $2 AND user_id = $3
        AND EXISTS (
          SELECT 1 FROM rerank_prompt_versions
           WHERE id = $1 AND prompt_id = $2
        )`,
    [opts.versionId, opts.promptId, opts.userId]
  );
  if (res.rowCount === 0) {
    throw new Error("prompt or version not found");
  }
}

export async function deleteRerankPrompt(
  id: string,
  userId: string
): Promise<void> {
  await query(
    `DELETE FROM rerank_prompts WHERE id = $1 AND user_id = $2`,
    [id, userId]
  );
}

// --- Search runs ---

export interface DbSearchRun {
  id: string;
  user_id: string;
  query: string;
  vector_k: number;
  rerank_k: number;
  rerank_enabled: boolean;
  prompt_version_id: string | null;
  filters_json: unknown;
  vector_hit_uris: string[];
  rerank_kept: unknown;
  ms_embed: number | null;
  ms_find: number | null;
  ms_hydrate: number | null;
  ms_rerank: number | null;
  ms_total: number | null;
  created_at: Date;
}

export async function insertSearchRun(run: {
  userId: string;
  query: string;
  vectorK: number;
  rerankK: number;
  rerankEnabled: boolean;
  promptVersionId: string | null;
  filtersJson: unknown;
  vectorHitUris: string[];
  rerankKept: unknown;
  msEmbed: number | null;
  msFind: number | null;
  msHydrate: number | null;
  msRerank: number | null;
  msTotal: number;
}): Promise<DbSearchRun> {
  const res = await query(
    `INSERT INTO search_runs
       (user_id, query, vector_k, rerank_k, rerank_enabled, prompt_version_id,
        filters_json, vector_hit_uris, rerank_kept,
        ms_embed, ms_find, ms_hydrate, ms_rerank, ms_total)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
     RETURNING *`,
    [
      run.userId,
      run.query,
      run.vectorK,
      run.rerankK,
      run.rerankEnabled,
      run.promptVersionId,
      JSON.stringify(run.filtersJson ?? null),
      run.vectorHitUris,
      run.rerankKept === null ? null : JSON.stringify(run.rerankKept),
      run.msEmbed,
      run.msFind,
      run.msHydrate,
      run.msRerank,
      run.msTotal,
    ]
  );
  return res.rows[0];
}

export async function listSearchRunsForUser(
  userId: string,
  limit: number = 20
): Promise<DbSearchRun[]> {
  const res = await query(
    `SELECT * FROM search_runs WHERE user_id = $1
      ORDER BY created_at DESC LIMIT $2`,
    [userId, limit]
  );
  return res.rows;
}

export async function getSearchRunForUser(
  id: string,
  userId: string
): Promise<DbSearchRun | null> {
  const res = await query(
    `SELECT * FROM search_runs WHERE id = $1 AND user_id = $2`,
    [id, userId]
  );
  return res.rows[0] ?? null;
}
